version: '3.8'

networks:
  app-network:

services:

  postgresql-db:
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=task_tl_db
      - POSTGRES_USER=task_tl
      - POSTGRES_PASSWORD=task_tl_password
    volumes:
      - ./db:/var/lib/postgresql/data
    networks:
      - app-network

  web:
    restart: always
    build:
      context: ./
    command: bash -c 'python ./src/manage.py migrate && python ./src/manage.py runserver 0.0.0.0:8000'
    ports:
      - "8000:8000"
    volumes:
      - .:/app/
    depends_on:
      - postgresql-db
    networks:
      - app-network
